services:
  mongodb:
    image: mongo:latest
    restart: always
    env_file: ".env"
    ports:
      - 9010:${MONGODB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: